site_name: SCKinect Documentation
site_description: Documentation for SCKinect - Motion Tracking for Sound Generation
site_author: Evan Murray
repo_url: https://github.com/L42i/SCKinect
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.twemoji

nav:
  - Home: index.md
  - Installation: installation.md
  - Getting Started: getting-started.md
  - Core Components:
    - Kinect UGen: components/kinect-ugen.md
    - User Input: components/user-input.md
    - User Output: components/user-output.md
  - API Reference:
    - Kinect Class: api/kinect-class.md
    - C++ Interface: api/cpp-interface.md
  - Examples:
    - Wind Sound: examples/wind.md
  - Contributing: contributing.md 
