on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Linux-x64
    env:
      SC_PATH: ${{ github.workspace }}/supercollider
      OPENPOSE_PATH: ${{ github.workspace }}/openpose
      LIBFREENECT_PATH: ${{ github.workspace }}/libfreenect2
      BUILD_PATH: ${{ github.workspace }}/build
      INSTALL_PATH: ${{ github.workspace }}/build/Install
      ARCHIVE_NAME: Kinect-${{ matrix.name }}.zip
    steps:
    - name: Checkout Kinect
      uses: actions/checkout@v3
    - name: Checkout OpenPose
      uses: actions/checkout@v3
      with:
        repository: AlecDusheck/openpose
        path: ${{ env.OPENPOSE_PATH }}
        ref: master
    - name: Checkout Libfreenect2
      uses: actions/checkout@v3
      with:
        respository: OpenKinect/libfreenect2
        path: ${{ env.LIBFREENECT_PATH }}
        ref: master
    - name: Checkout SuperCollider
      uses: actions/checkout@v3
      with:
        repository: supercollider/supercollider
        path: ${{ env.SC_PATH }}
        ref: main
    - name: Create Build Environment
      shell: bash
      run: cmake -E make_directory $BUILD_PATH
    - name: Install OpenPose Dependencies
      shell: bash
      working-directory: ${{ env.OPENPOSE_PATH }}
      run: sudo apt-get install libopencv-dev && sudo bash ./scripts/ubuntu/install_deps.sh
    - name: Configure CMake
      shell: bash
      working-directory: ${{ env.BUILD_PATH }}
      run: cmake .. -DCMAKE_BUILD_TYPE='Release' -DSC_PATH="$SC_PATH" -DCMAKE_INSTALL_PREFIX="$INSTALL_PATH"
