on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Linux-x64
    env:
      SC_PATH: ${{ github.workspace }}/supercollider
      OPENPOSE_PATH: ${{ github.workspace }}/openpose
      BUILD_PATH: ${{ github.workspace }}/build
      INSTALL_PATH: ${{ github.workspace }}/build/Install
      ARCHIVE_NAME: Kinect-${{ matrix.name }}.zip
    steps:
    - name: Checkout Kinect
      uses: actions/checkout@v3
    - name: Checkout OpenPose
      uses: actions/checkout@v3
      with:
        repository: AlecDusheck/openpose
        path: ${{ env.OPENPOSE_PATH }}
        ref: master
    - name: Checkout SuperCollider
      uses: actions/checkout@v3
      with:
        repository: supercollider/supercollider
        path: ${{ env.SC_PATH }}
        ref: main
    - name: Create Build Environment
      shell: bash
      run: cmake -E make_directory $BUILD_PATH
